### ISSUE TITLE
__DEV__ is not defined

### ISSUE THREAD

**Issue by patrickml** [vincee48/react-native-checkbox-field#2]
When installed I am getting this error

```
TransformError: /Users/patricklewis/Documents/sites/react-native/flex/node_modules/react-native-checkbox-field/index.js: __DEV__ is not defined
```

Whats odd is i don't see __DEV__ used in your source. Any idea what might be going on? Removing the npm package fixed my issue.

**Comment by vincee48** [comment]
I've updated the package and removed some dependencies, as well as upgraded to the latest React + React Native with an example project. Please update the package and try again - hopefully this will resolve the issue!

**Comment by patrickml** [comment]
thank you @vincee48
