### ISSUE TITLE
Label on either side of checkbox

### ISSUE THREAD

**Issue by ssomnoremac** [vincee48/react-native-checkbox-field#3]
I think this is a missing part of what would make this fully customizable. Would suggest:

    labelOnLeft={true}

and then I don't know the best way to rearrange on the `render()`. Perhaps 

    {LabelOnLeft}
    <CheckBox ..>
    {LabelOnRight}

and just set one or the other to null. Or maybe through absolute positioning?

**Comment by vincee48** [comment]
Sounds like a reasonable enhancement - I'll set that up soon. Happy to accept any PRs if you get there before I can!

**Comment by vincee48** [comment]
react-native-checkbox-field@1.0.9 now includes the ability to add a "labelSide" prop with values "left" or "right", defaulting to "left".
